language: csharp
mono: none
dotnet: 2.2.202
solution:  QQWrySln.sln
scripts:
  - dotnet restore
  - dotnet build QQWrySln.sln
  - dotnet test .\QQWryTest -c Release
  - dotnet pack .\QQWry
  - dotnet pack .\QQWry.DependencyInjection